<?php
return array(
	array(
		'title'=>'cms管理',
		'menu'=>array(
			'direction'=>'v',
			'independence'=>true,
			'items'=>array(
				array(
					'title'=>'文章管理',
					'link'=>'?c=org.opencomb.opencms.article.ArticleManage'
				),
				array(
					'title'=>'栏目管理',
					'link'=>'?c=org.opencomb.opencms.category.CategoryManage'
				)
			)
		)
	)
);